# Generated by Django 4.2.7 on 2023-12-07 04:33

import contact.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('passport_serial', models.CharField(blank=True, max_length=9, null=True, validators=[contact.validators.validate_passport_serial])),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=5, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('plastikraqam_ozi', models.IntegerField(blank=True, null=True)),
                ('plastikraqam_gumondor', models.IntegerField(blank=True, null=True)),
                ('full_name_gumondor', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_gumondor', models.CharField(blank=True, max_length=32, null=True)),
                ('sana', models.DateField(blank=True, null=True)),
                ('vaqt', models.DateTimeField(blank=True, null=True)),
                ('summa', models.IntegerField(blank=True, null=True)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='chek_rasm/')),
                ('ilova', models.CharField(blank=True, max_length=50, null=True)),
                ('ilova_gumondor', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HujumTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hujum_name', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField(null=True)),
                ('img', models.ImageField(null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('tekshirilmoqda', 'Tekshirilmoqda'), ('tekshirildi', 'Tekshirildi'), ('rad etildi', 'Rad etildi'), ("ma'lumot topilmadi", "Ma'lumot topilmadi")], default='yangi', max_length=20, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_create', to='contact.application')),
            ],
            options={
                'ordering': ['-update', '-createdate', '-id'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.tuman'),
        ),
        migrations.AddField(
            model_name='application',
            name='hujumturi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.hujumturi'),
        ),
    ]
