# Generated by Django 4.2.7 on 2023-12-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='plastikraqam_gumondor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='plastikraqam_ozi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
