# Generated by Django 4.2.7 on 2023-12-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hujumturi',
            old_name='text',
            new_name='hujum_text',
        ),
    ]
