# Generated by Django 4.2.5 on 2023-12-02 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_application_plastikraqam_gumondor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='username',
            new_name='surname',
        ),
    ]
