# Generated by Django 4.2.7 on 2023-12-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_text_hujumturi_hujum_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcreate',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_create', to='contact.application'),
        ),
    ]
