# Generated by Django 4.2.5 on 2023-12-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_username_application_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcreate',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationcreate',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('tekshirilmoqda', 'Tekshirilmoqda'), ('rad etildi', 'Rad etildi'), ('tekshirildi', 'Tekshirildi')], default='yangi', max_length=14, null=True),
        ),
    ]
