# Generated by Django 4.2.7 on 2023-12-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
